version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./containers/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/pong:/var/www/game/
    restart: on-failure