services:
  web:
    container_name: web
    build:
      context: ./containers/transcendence
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: neo
      DATABASE_PASSWORD: dansmatrix
      DATABASE_NAME: tr_database
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - postgres
############################
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tr_database
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: dansmatrix
    env_file:
      - ./.prod.db.env
############################
  nginx:
    volumes:
      - static_volume:/home/app/web/staticfiles
    container_name: nginx
    build: ./containers/nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  # pgadmin_data: