version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=neo
      - POSTGRES_PASSWORD=dansmatrix
      - POSTGRES_DB=tr_database
    env_file: .env
  web:
    container_name: web
    build: ./containers/transcendence
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./containers/transcendence/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
volumes:
  postgres_data: