version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./containers/transcendence
      dockerfile: Dockerfile.prod
    command: gunicorn transcendence.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - postgres
############################
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod.db.env
############################
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: neo@dansmatrix.com
      PGADMIN_DEFAULT_PASSWORD: dansmatrix
      POSTGRES_DB: tr_database
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: dansmatrix
    env_file:
      - ./.prod.db.env
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_setup:/pgadmin_setup
    entrypoint: ["/pgadmin_setup/entrypoint.sh"]
############################
  nginx:
    volumes:
      - static_volume:/home/app/web/staticfiles
    container_name: nginx
    build: ./containers/nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  pgadmin_data: